# Generated by Django 5.0.1 on 2024-01-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_blog_delete_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
