# Generated by Django 5.0.1 on 2024-01-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_name',
            new_name='title',
        ),
    ]
