# Generated by Django 5.0.1 on 2024-01-31 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_rename_version_name_version_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='version',
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='продукт'),
        ),
    ]
