# Generated by Django 5.0.1 on 2024-01-31 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_remove_version_version_alter_version_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='version_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Номер версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='current_version',
            field=models.BooleanField(default=True, verbose_name='Актуальна'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название версии'),
        ),
    ]
