# Generated by Django 5.0.1 on 2024-02-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_rename_current_version_version_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='is_active',
            new_name='is_current',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='title',
            new_name='version_name',
        ),
    ]
