# Generated by Django 5.0.1 on 2024-02-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_product_author'),
    ]

    operations = [
        migrations.RunSQL('UPDATE goods_product SET author_id = 1 WHERE author_id IS NULL;'),
    ]
